# Generated by Django 2.0.1 on 2020-02-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200209_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
